services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=storeDB'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
