services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=storeDB
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

#  stripe:
#    image: 'stripe/stripe-cli:latest'
#    container_name: stripe
#    environment:
#      - STRIPE_API_KEY=whsec_37075ac283e1e6a9904f7037f25cf6277d2943a7933c60d8e25f6a4140e01331
#    command: listen --forward-to host.docker.internal:8080/api/payment/webhook
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  mongo-data:
  redis-data:
